# Generated by Django 5.1.1 on 2024-11-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("year", models.CharField(max_length=64)),
                ("genre", models.CharField(max_length=64)),
                ("rating", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=64)),
                (
                    "movies",
                    models.ManyToManyField(
                        blank=True, related_name="watchers", to="ShowTimeApp.movies"
                    ),
                ),
            ],
        ),
    ]
